apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: example-nfs
  resources:
    requests:
      storage: 10Gi
