apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: ic-webapp
  labels:
    app: odoo
    env: prod
spec:
  type: NodePort
  selector:
    app: odoo
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
      nodePort: 30069
