apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pvc
  namespace: ic-webapp
  labels:
    app: odoo
    env: prod
spec:
  storageClassName: manual
  volumeName: odoo-pv  
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
